name: devfestapp
description: A web app for DevFest 2022, powered by Flutter. Showcasing the
  speaker's profile, schedule, and more.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  responsive_grid: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/speakers/
    - assets/svg/
